vector_unit:
  lanes: 128
  sublanes: 8
  ALUs_per_sublanes: 4

matrix_unit:
  mxu_dimension: 128
  num_mxus: 4

memory:
  mem_size: 262144
  mem_type: spad
  policy: oracle
  access_granularity: 128
